class _BotCommands:
    def __init__(self):
        self.StartCommand = '782start'
        self.MirrorCommand = 'mega'
        self.UnzipMirrorCommand = '988unpack'
        self.TarMirrorCommand = '399tarmirror'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = '39cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = '738authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = '889stats'
        self.HelpCommand = '999help'
        self.LogCommand = '777log'
        self.SpeedCommand = '988speedtest'
        self.CloneCommand = '877clone'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.UsageCommand = '977usage'
        self.OwnerCommand = '887owner'

BotCommands = _BotCommands()
